### ISSUE TITLE
async abilities

### ISSUE THREAD

**Issue by knownasilya** [minutebase/ember-can#20] opened 2015-07-09 12:23 UTC
Maybe supporting promises by returning a promise since resolving/rejecting is like true/false. This would make these much more powerful.

**Comment by blimmer** [comment] 2015-07-09 12:41
Can you provide an example of a situation where an async ability would be useful? I'm struggling to come up with an example where it'd be more useful than the boolean. If it's something that would be useful to a lot of people, I'm open to implementing it in this package. If not, you could easily implement this for your needs by creating a new mixin like this:

```javascript
import { CanMixin } from 'ember-can';

export default Ember.Mixin.create(CanMixin, {
  asyncCan: function(abilityName, resource, additionalProperties) {
     var can = can(abilityName, resource, additionalProperties);
     if (can) {
      return new Ember.RSVP.Promise.resolve();
     } else {
      return new Ember.RSVP.Promise.reject();
     }
  }
});
```

**Comment by knownasilya** [comment] 2015-07-09 12:46
The idea is that you don't know the result of can until the promise has fulfilled, like if you have async models that need to be first resolved, or an ajax promise upon which the ability depends.

**Comment by rlivsey** [comment] 2015-07-09 12:47
I think this would be difficult to implement until Ember itself is more promise aware.

I know there's talk/work in making streams and computed properties promise aware, at which point it would be possible to implement here - or actually I think we'd get it for free.

**Comment by GabKlein** [comment] 2015-09-01 11:06
Here an example where the async support would be useful:

```javascript
import Ember from 'ember';
import { Ability } from 'ember-can';

export default Ability.extend({
  canDelete: Ember.computed('currentUser.user', 'currentOrganization.organization', function() {
    var organization = this.currentOrganization.organization;
    var user = this.currentUser.user;

    return organization.isOwner(user).then(function(isOwner) {
      return isOwner;
    });
  }),

  canAdd: Ember.computed('currentUser.user', 'currentOrganization.organization', function() {
    var organization = this.currentOrganization.organization;
    var user = this.currentUser.user;

    return organization.isOwner(user).then(function(isOwner) {
      return isOwner;
    });
  })
});
```

**Comment by olivierchatry** [comment] 2015-09-02 14:59
Looked a bit on how to do that, for now the only idea I can come up with would be to have a function that return the dependent key for an action inside the ability, then we hook an observer on them that call recompute. 

The other modification possible is in Ember ( modify the Helper class to support promise ). That might be more desirable as they seems to want to go all the way async.

**Comment by olivierchatry** [comment] 2015-09-03 09:07
Ok I found a workaround :
```javascript
import Ember from 'ember';
import { Ability } from 'ember-can';


export default Ability.extend({
  isAdminObserver: Ember.observer(
    'session.currentUser.backendAccountsAdmin.[]',
    'session.accounts',
    function() {
      return this.get('session.currentUser').then(
        (user) => {
          if (user.get('isSuperAdmin')) {
            this.set('canManage', true)
          } else {
            return user.get('backendAccountsAdmin').then(
              (accounts) => {
                this.set('canManage', !this.get('canManage'))
              }
            )
          }
        }
      )
    }
  ),
  canManage: Ember.computed(function() {
    let content = this.get('session.currentUser.content')
    if (content) {
      content = content.get('backendAccountsAdmin.content')
      if (content) {
        return content.contains(this.get('model'))
      }
    }
    return false
  })
})
```

It is actually fairly simple : 
ember-can hookup an observer on the name of the ability, so whenever you call set on the name of your ability (for me "canManage"), and if the value is different, it will trigger a recompute of the value.

From here, we now that when an async object is fullfilled, the data are present in the 'content' attribute. 
so basically, you need to start the async query, then when it is complete, set the ability to the value you where getting ( it will be lost, but the important part is that it will trigger a recompute of the helper in case the current and previous value are different ). 

Your ability should then just check for the "content" object present, and then fetch the values from here.

In my case ( code above ), I got user, which are async, and a table inside that tells me which account the user is admin of. So I got two premise to do : first get the user, then the table. 
when the table is there, then I set the value. 
Note that the main problem here is that the that "model" is not accessible in the observer, it is not really important anyway, because what you really want is just to be sure to call recompute, so just put a value in the ability property that is different from the current one.

Hope it make senses.

**Comment by rlivsey** [comment] 2015-09-03 09:50
If at all possible I'd recommend avoiding observers, they're a big bag of nuance and potential foot-guns!

A pattern I've used in the past where I have computed properties which are promise based is as follows:

```javascript
foo: Ember.computed("other", "properties", {
  get() {
    // fetches the thing when the CP is consumed and then sets itself when done
    this.get("somethingAsync").then(val => {
      this.set("foo", val);
    });

    // in the meantime, return null (or whatever the pre-resolved value wants to be)
    return null;
  },
  set(k, val) {
    return val;
  }
})
```

This could quite easily be wrapped up to provide a nicer API like the following which cleans up the boilerplate:

```javascript
foo: Ember.computed.promise("other", "properties", () => this.get("somethingAsync"));
```

Could make a nice generic addon, and in the future hopefully it's something Ember itself is more capable of.

**Comment by olivierchatry** [comment] 2015-09-03 10:27
I'm not sure that would work with helpers though. But if it does, it looks way better than what I have.

**Comment by JoshSmith** [comment] 2016-12-06 01:57
I just got bit by this today.

I'm using `ember-can` in both routes and templates.

- In routes, I want to be able to direct transitions in a `beforeModel()` hook depending on whether someone has permission to do so.
- In templates, my behavior is pretty standard.

My use case is _extremely_ similar to @GabKlein's in the comment here: https://github.com/minutebase/ember-can/issues/20#issuecomment-136675964

**Comment by ashrafhasson** [comment] 2017-07-05 19:14
using an injected service, such as a current-user or an account that fetches data from remote locations, is one use case I was trying to implement. I get `RangeError: Maximum call stack size exceeded` when attempting to compute properties that read an ability's property.

**Comment by ashrafhasson** [comment] 2017-07-05 20:19
`RangeError: Maximum call stack size exceeded` was caused by `computed.ability` attempting to set the `controller` content to the `ability`'s model which was set to the `route`'s model. My fault for missing this detail!

**Comment by ashrafhasson** [comment] 2017-07-10 19:47
Hi there,

Is support for async checks something being considered?

Thanks,

**Comment by achambers** [comment] 2018-03-13 16:05
Hi,

Is this repo still maintained? What’s happening with this issue? It’s been open for 2 years. 

Hello? Anybody there?

**Comment by blimmer** [comment] 2018-03-13 16:10
@achambers please see https://github.com/minutebase/ember-can/issues/67#issuecomment-370901186 and check with @exelord

**Comment by rlivsey** [comment] 2018-03-13 17:13
@achambers thanks for the nudge 😏

**Comment by basz** [comment] 2018-12-05 13:42
Hi,

Just wanted to chip in, I got async abilities working with some help of [ember-promise-helpers](https://github.com/fivetanley/ember-promise-helpers).

If there is a better way I'm interested.

```js
/**
   * Does the order belongs to (the as set as defined preferred) customer.
   *
   * @return EmberPromise
   */
  belongsToPreferredProfile: computed('order', 'account.selectedCustomer', function() {
    const order = this.get('order');
    const selectedCustomer = this.get('account.selectedCustomer');

    return new EmberPromise((resolve, reject) => {
      if (isNone(order) || isNone(selectedCustomer)) {
        return reject();
      }

      const selectedCustomerId = selectedCustomer.get('id');

      order
        .get('dossier.owningCustomer')
        .then(customer => {
          const owningCustomerId = customer.get('id');

          if (owningCustomerId !== selectedCustomerId) {
            return reject();
          }

          return resolve();
        })
        .catch(() => reject());
    });
  }),
```

```hbs
{{#with (can "dossierOrder.belongsToPreferredProfile" order=orderStepManager.order) as |canPromise|}}
    {{#if (is-pending canPromise)}}
      contemplating
    {{else}}
      {{#if (is-fulfilled canPromise)}}
        Yay it worked!
      {{/if}}
      {{#if (is-rejected canPromise)}}
        never mind
      {{/if}}
    {{/if}}
  {{/with}}
```

**Comment by Exelord** [comment] 2018-12-12 11:09
I think this may help close this issue: https://medium.com/macsour/how-to-handle-async-abilities-with-ember-can-22d90df056ed

**Comment by Exelord** [comment] 2018-12-18 20:20
Feel free to open it again

**Closed by Exelord** 2018-12-18 20:20 UTC
